name: "Install metal extra dev dependencies - ubuntu-20.04"
description: "Installs tt-metal extra dev dependencies on ubuntu-20.04 GitHub Actions
runners"

inputs:
  os:
    description: 'Runner OS'
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify ubuntu only
      shell: bash
      run: |
        if ! echo ${{ inputs.os }} | grep -q "ubuntu"; then
          echo "${{ inputs.os }} does not seem to be ubuntu"
        fi
    - name: Assert requested os exists in dependencies
      shell: bash
      run: |
        if ! jq -e ".\"${{ inputs.os }}\" != null" $GITHUB_ACTION_PATH/dependencies.json; then
          echo "${{ inputs.os }} does not exist as a supported os in $GITHUB_ACTION_PATH/dependencies.json"
        fi
    - name: Retrieve and install pkg deps based on OS
      id: retrieve-pkg-deps
      shell: bash
      run: |
        DEPENDENCIES=$(jq -r --arg os "${{ inputs.os }}" '.[$os] | .[]' $GITHUB_ACTION_PATH/dependencies.json)
        echo $DEPENDENCIES
        sudo apt update
        sudo apt install $DEPENDENCIES
    - name: Install doxygen
      shell: bash
      run: |
        curl -L "https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz" -o doxygen-1.9.6.linux.bin.tar.gz
        tar -xvf doxygen-1.9.6.linux.bin.tar.gz
        cd doxygen-1.9.6
        sudo make install
    - name: Install gtest
      shell: bash
      run: |
        curl -L "https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz" -o v1.13.0.tar.gz
        tar -xvf v1.13.0.tar.gz
        cd googletest-1.13.0
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON .
        make
        sudo make install
    - name: Install clang-17
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 17
        clang-17 --version
