name: "[post-commit] all - Static checks, linters etc."

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - "main"

jobs:
  check-spdx-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: infra/requirements-infra.txt
      - name: Install infra deps
        run: python -m pip install -r infra/requirements-infra.txt
      - name: Check SPDX licenses
        run: python -m check_copyright --verbose --dry-run --config ./check_copyright_config.yaml .
  check-metal-kernel-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check kernel count in base metal is less than maximum
        run: if (( $(find tt_metal/kernels/ -type f | wc -l) > 7 )); then exit 1; fi
  check-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@23.10.1
  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      - name: Fetch merge target
        if: ${{ github.event_name == 'pull_request' && github.ref != 'refs/heads/main' }}
        run: git fetch origin $GITHUB_BASE_REF --depth=1
      - name: Run formatter
        if: ${{ github.event_name == 'pull_request' && github.ref != 'refs/heads/main' }}
        run: BASE_COMMIT_SHA=origin/$GITHUB_BASE_REF scripts/lint_clang_format.sh -m diff
      - name: Run formatter against previous commit (main only)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: BASE_COMMIT_SHA=${{ github.event.before }} scripts/lint_clang_format.sh -m diff
  check-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ASPELL
        run: sudo apt-get install -y aspell
      - name: Run checks on docs
        run: TT_METAL_HOME=$(pwd) docs/spellcheck.sh
