name: "[post-commit] C++ tests"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  # build-artifact:
  #   uses: ./.github/workflows/build-artifact.yaml
  #   secrets: inherit
  cpp-unit-tests:
    # needs: build-artifact
    uses: ./.github/workflows/cpp-post-commit.yaml
    secrets: inherit
