---
name: "[post-commit] eager - Package on main"

on:
  workflow_dispatch:
  workflow_call:

# TODO: RK - need to change this to every push later once
# we go public
jobs:
  build-eager-package:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        arch: [grayskull, wormhole_b0]
    uses: ./.github/workflows/eager-package.yaml
    with:
      environment: dev
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
  test-eager-package-host:
    needs: build-eager-package
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        arch: [grayskull, wormhole_b0]
    runs-on: ${{ matrix.os }}
    environment: production
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false
      - uses: ./.github/actions/install-metal-deps
        with:
          os: ${{ matrix.os }}
      - uses: actions/download-artifact@v4
        with:
          name: eager-dist-${{ matrix.os }}-${{ matrix.arch }}
      - name: Set up end-to-end tests environment
        run: ./tests/scripts/set_up_end_to_end_tests_env.sh
      - name: Set up dynamic env vars
        run: |
          source tests/end_to_end_tests/env/bin/activate
          python3 -m tt_metal.scripts.get_home_dir --short
          echo "TT_METAL_HOME=$(python3 -m tt_metal.scripts.get_home_dir --short)" >> $GITHUB_ENV
      - name: Activate env and run release tests - host
        shell: bash
        run: |
          source tests/end_to_end_tests/env/bin/activate
          ./tests/scripts/run_tests.sh --tt-arch ${{ matrix.arch }} --pipeline-type eager_host_side
  test-eager-package-silicon:
    needs: build-eager-package
    strategy:
      matrix:
        os: [ubuntu-20.04]
        runner-hw-info: [
          {arch: grayskull},
          {arch: wormhole_b0},
        ]
    runs-on: ["Linux", "${{ matrix.runner-hw-info.arch }}"]
    environment: production
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.runner-hw-info.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false
      - uses: actions/download-artifact@v4
        with:
          name: eager-dist-${{ matrix.os }}-${{ matrix.runner-hw-info.arch }}
      - name: Set up end-to-end tests environment
        run: ./tests/scripts/set_up_end_to_end_tests_env.sh
      - name: Set up dynamic env vars
        run: |
          source tests/end_to_end_tests/env/bin/activate
          python3 -m tt_metal.scripts.get_home_dir --short
          echo "TT_METAL_HOME=$(python3 -m tt_metal.scripts.get_home_dir --short)" >> $GITHUB_ENV
      - name: Set up kernel builds
        run: |
          source tests/end_to_end_tests/env/bin/activate
          python3 -m tt_metal.scripts.set_up_kernels --short prepare
      - name: Activate env and run release tests - silicon
        shell: bash
        run: |
          source tests/end_to_end_tests/env/bin/activate
          ./tests/scripts/run_tests.sh --tt-arch ${{ matrix.runner-hw-info.arch }} --pipeline-type eager_package_silicon
